
== Output console.log()

Let's start with a really simple program.
Perhaps the simplest JavaScript program is 

[source,JavaScript]
----
console.log("Hello, World!");
----

This program just prints "Hello, World!". footnote:[And while you might _not yet_ understand this _technical description_, it is a program of one _line_ of code, which says "call the 'log' method on the 'console' object, using the string "Hello, World!" as the argument to be logged."]

Logging, in this case, means _outputting_ or _printing_ the "Hello, World!" somewhere. That somewhere is the _console_ a place JavaScript uses to communicate with a user (in this case, us, the programmers.)

(And if you haven't done it yet, go to https://repl.it and create an account for yourself. Once that's done you should create a JavaScript repl, a place where you can type the code from this book to the repl and run it, to see what each code snippet does.)

We will use `console.log` to do a lot in the coming pages. It's a simple statement, one that in other languages might be `print` or `write` or `puts` (and why we all cannot just agree on one way to do this, well, beats me. JavaScript's is `console.log`)

Here's your second JavaScript program: 

```JavaScript
let milesPerHour = 55.0;
console.log("Car's Speed: ", milesPerHour);
```

Which, if you typed into your repl and clicked the "Run >" button, you saw

****
Car's Speed:  55
****

as the program's output.

Cool, huh? The ability to communicate with you is one of JavaScript's most fundamental capabilities. And you've run two js programs. Congratulations, you're a coder. (well, at least for today you are.)

== Comments

While you're not thinking about the long term, or about large JavaScript programs, there is a powerful thing in JavaScript that helps with tracking comments and notes about the code.

In your program you can write stuff that JavaScript will ignore, it's just there for you (or readers of your code).

```
// This comment occupies a line of its own
console.log('Hello');

console.log('World'); // This comment follows the statement
```

Often, you'll see something like this in this book.

```
let flourAmount = 3.5;

console.log(flourAmount); // -> 3.5
```

That comment at the end of the concole.log line is showing what you can expect to see in the output. Here it would be "3.5" printed by itself.

We can also added useful stuff to the .log call. 

```
let flourAmount = 3.5;

console.log("We need", flourAmount, "cups of flour."); // -> We need 3.5 cups of flour.
```

See how JavaScript types it all out as a useful phrase? That proves to be very handy in a million-plus cases.

Comments can be used to explain tricky bits of code, or describe what you should see in output. Comments are your friend. 

== Statements and Expressions

In JavaScript there are parts of a program and different parts have different names. Two of the most basic (and fundamental) are *statements* and *expressions*.

=== Expressions

An *expression* is something that needs to be computed to find out the answer. Here's a few simple ones.

```
2 + 2 * 65536

speed > 55.0

regularPrice * (1.0 - salePercentOff)
```

Each of these lines is someting we'd like JavaScript to *compute* for us. That computation is often referred to as "evaluation" or "evaluate the expression" to get to the answer. There are two kinds of expressions in JavaScript, _arithmetic expressions_ and _boolean expressions_.

*Arithmetic expressions* are, as their name implies, something that require arithmetic to get the answer. An expression like "5 + 8 - 3" gets _evaluated_ to 10.

*Boolean expressions* result in either a True or a False value. Example: "maxSpeed > 500.0" - this is either true or false depending on the value of maxSpeed.

=== Statements

A *statement* is just a line of JavaScript. It ends with a ';' (semi-colon).

```
// at the Grocery

salesTaxRate = 0.06;

totalGroceries = 38.99;
salesTax = totalGroceries * salesTaxRate;

chargeToCard = totalGroceries + salesTax;
```
And this is what a JavaScript program looks like. It's just a list of statements, one after the other, that get computed from the top down.

Some of the statements have expression in them (like totalGroceries * salesTaxRate), some are just simple *assignment* statements (like totalGroceries = 38.99, where we assign the variable 'totalGroceries' the value 38.99) Don't panic, thse are just some simple examples of JavaScript to give you a feel for it. We'll go thru each of these kinds of things slowly in sections ahead.

=== Multi-line Statements

In this book, you may see that the code used in examples is longer than can fit on one line in the code boxes. Well, JavaScript doesn't care, that's why it has *semi-colons* ';' at the end of the statements. So to be clear, a statement with long variable names is the same as one with a short name.

```
k = h * kph - (rest / 60);

kilometersCycled = numberOfHoursPedalled * kilometersPerHour - (totalMinutesOfRest / 60);
```

When you come across code that goes onto multiple lines, do like JavaScript does, read until you find the ';'. It's like a period in an english sentence.

=== Block Statement

Very often in JavaScript we will see a *block* of statements. It is a list of statements inside of a pair of curly-braces "{ }". It acts like a container to make clear what statements are included in the block.

```
if (magePower > 120.0) {
    maxMagic = 500.0;
    lifeSpan = 800.0;
    maxWeapons = magePower / maxPowerPerWeapon;
}

// some more code
```

See those curly-braces? They start and stop the _block_, and contain the statements within. You can also see how the code is indented, but the real key are those braces. You'll see lots of blocks when you're looking at JavScript code.

