
== Conditional Statements

While we have been seeing programs which consist of of a list of statements, one after another, where the "flow of control" goes from one line to the next, and so on to the end of the list of lines.
There are more useful ways of breaking up the "control flow" of a program. JavaScript has several conditional statements that let the programmer do things based on conditions in the data. 

== If statement

The first conditional statement  is the *if* statement.

```
if (something-is-true) doSomething;
```

Here are a few simple examples.

```
if (speed > speedLimit) driver.getsATicket();

if (x <= -1) console.log("Cannot have negative numbers!");

if (account.balance >= amountRequested) {
    subtract(account, amountRequested);
    produceCash(ammountRequested);
    printReceipt(amountRequested);
}
```

JavaScript also has an *else* part to the *if* statement. When the *if* condition is False, the else part gets run.

```
if (account.balance >= amountRequested) {
    // let customer have money
} else {
    printReceipt("Sorry, you don't have enough money in your account!")
}
```

[source, js]
----
let timeOfDay = "Afternoon";
if (timeOfDay == "Morning") {
    console.log("Time to eat breakfast");
} else if (timeOfDay == "Afternoon") {
    console.log("Time to eat lunch");
} else {
    console.log("Time to eat dinner");
}
----

[TIP]
====
Write code to check if a user is old enough to drink.

* if the user is under 18. Print out "Cannot party with us"
* Else if the user is 18 or over, Print out "Party over here"
* Else print out, "I do not recognize your age"
====
You should use an if statement for your solution!

Finally, make sure to change the value of the age variable in the repl, to output out different results and test that all three options can happen. What do you have to do to make the `else` clause happen?

(should there be a page break here?)

==== If Statement solution
[source, js]
----
let userAge = 17;
if (userAge < 18) {
console.log("Cannot party with us");
} else if (userAge >= 18) {
console.log("Party over here");
} else {
console.log("I do not recognize your age");
}
----


(more...)