== Operators
=== Arithmetic Operators

[cols=",,",options="header",]
|===
|Operator |Name |Description
|+ |Addition |Add two values
|- |Subtraction |Subtract one from another
|* |Multiplication |Multiply 2 values
|/ |Division |Divide 2 numbers
|% |Modulus |returns the remainder
|++ |Increment |Increase value by 1
|- - |Decrement |Decrease value by 1
|===

=== Demo of Arithmetic Operators

Say we needed to multiply two numbers. Maybe 2 times 3. Now we could easily write a program
that printed that result.

```
console.log(2 * 3); 
```
And that will print 6 on the console. But maybe we'd like to make it a little more
complete.

[source, js]
----
let a = 2; 
let b = 3;
// Multiply a times b
let answer = a * b;
console.log(answer); // -> 6
----

Using this as a model, how would you write programs to solve these problems?

[TIP]
====
* Lab 1: Subtract A from B and print the result
* Lab 2: Divide A by B and print the result
* Lab 3: Use an operator to increase A by 1 and print result
====

[source, javascript]
----
let a = 9; 
let b = 3;

let L1 = b - a;
let L2 = a / b;
let L3 = a + 1;
//or
L3 = a++;
console.log(L1); // -> -6
console.log(L2); // -> 3
console.log(L3); // -> 10
----

=== How about Modulus|remainder

Now what's this about '%' (the remainder) operator?

[source, js]
----
let a = 2; let b = 3;
//Modulus
let answer = b % a;
console.log(answer); // -> 1
----

=== How about Modulus|remainder
[source, js]
----
let a = 4; let b = 19;
//Modulus
let answer = b % a;
console.log(answer); // -> 3
----

=== order of operations

==== P.E.M.D.A.S
"Please Excuse My Dear Aunt Sally"

* Parenthesis ( )
* Exponents 2<sup>3</sup>
* Multiplication *
* Division / 
* Addition + 
* Subtraction - 


=== Note
Divide and Multiply rank equally (and go left to right).

Add and Subtract rank equally (and go left to right)


=== Order of operations
30 + 6 × 2

what should be solved first?


Best way to solve for 30 + 6 × 2

is

* First 6 × 2 = 12, then 30 + 12 = 42


=== Solve using JavaScript
[source, js]
----
let a = 30;
let b = 6;
let c = 2;
let multi = b * c;
let result = a + multi;
console.log(result);
----
=== Order of operations
(30 + 6) × 2

What should be solved first?


Best way to solve for (30 + 6) × 2 

is
* First 30 + 6 = 36 , then 36 × 2 = 72


=== Micro Lab
(30 + 6) × 2

Now, Your turn to solve the equation with JS


=== Solution to Micro Lab
[source, js]
----
let a = 30;
let b = 6;
let c = 2;
let multi = a + b;
let result = multi * c;
console.log(result);
----

=== JavaScript Math Object
The JavaScript Math object allows you to perform mathematical tasks on numbers.


=== JS Math Object Methods

* Math.PI; - returns 3.141592653589793
* Math.pow(x, y) - the value of x to the power of y - x<sup>y</sup>
* Math.sqrt(x) - returns the square root of x



=== Math.Pow( ) Demo

* 30 + 6<sup>2</sup> × 2
How to solve?
* First 6 * 6 = 36 , then 36 * 2 = 72 , then + 30 = 102


=== Micro Lab
30 + 6<sup>2</sup> × 2

Now, Your turn to solve the equation with JS

=== Solution to Micro Lab
[source, js]
----
let a = 30;
let b = 6;
let c = 2;
let powerOf = Math.pow(b, c); // (6, 2) -> 36
let multi = powerOf * c; // 36 * 2 -> 72
let result = multi + a; // 72 + 30 -> 102
console.log(result); // -> 72
----
