== Variables and Data Types

=== What are variables?

In JavaScript, variables are containers used to store data while the program is running. Variables can be named just about anything, and often are named things that make you think about what you store there.

```

```

(need more)

- Variables must be named.
- Names can contain letters, digits, underscores, and dollar signs
- Names must begin with a letter
- Names can also begin with $ and _ 
- Names are case sensitive (y and Y are different variables)
- Reserved words (like JavaScript keywords) cannot be used as names
- All variable names must be unique (no two alike)

=== JavaScript Data Types

JavaScript primitive Data Types:

- Number - integers, floats - 1, 1.7
- String - an array of characters - 'text' or "Hello!"
- Boolean - true or false
- Null - no value
- Undefined - a variable not yet assigned - let x;

==== Declaring a Variable

```
let x;
```
This creates a variable *x* that can hold any primitive type. But it has NO value assigned to it, so if we...

```
console.log(x);  // -> undefined
```
There is _nothing_ there. 

If we were to, declare a variable named cats, and assign it the value 3. 

```
let cats = 3;
console.log(cats);  // -> 3
```

==== Assign a value to a variable

```
let x = 19; 
console.log(x); // -> 19
```

==== Reassigning a value to a variable

```
x = "nineteen";
console.log(x); // -> nineteen
```

In JS, variables are dynamic (can contain any data) which means a variable can be a string and later be a number.

=== Constants

Constants are like let variables but they contain values that do NOT change such as a person’s date of birth. Convention is to capitalized constant variable names.

```
const DATE_OF_BIRTH = "04-02-2005";
DATE_OF_BIRTH = "04-10-2005"; // <-error
```
An attempt to re-assign a value to a constant will fail.




==== Mini Lab

Create variables for primitive data type below:
boolean, float, integer, string and a constant
Store some values in each and print them out




==== Mini Lab

```
let x=0;
let playerOneAlive = true;
let currentSpeed = 55.0;
let playerOneName = "Rocco";
const maxPainScore = 150000;
```


