
Let's look at a series of problems that you can solve to get a feel for what we're looking for on the Zip Code admissions assessment.
If you're able to reason through these problems, you should just fine on the assessment.

Feel free to use the https://code.zipcode.rocks REPL to work these problems out. 
(You can also just work them out in your head or on paper)

Computing is often programming a computer to do math. 
The use of variables, like in algebra, can make the computation quite flexible.
By solving these problems, you'll get a feel for the kind of easy algebra problems we'd like you to be able to solve.

As with many kinds of programming tasks, these problems can be solved a large number of ways.

=== Y equals ?

Look at each of these formulas, and determine what *y* is based on substituting the given value of *x*.

----
If y = 3x + 5 and x = 2
----

****
x = 2

y = 3x + 5

y = (3 times x) plus 5

y = (3 times 2) plus 5

y = 6 plus 5

y = 11
****

Now, here are a few problems for you to solve.

==== ?

----
Given the following formula,
 
y = 6x - 7

what is y, if x = 2?
----

==== ?

----
Given the following formula,
 
y = 3x + 8

what is y, if x = 5?
----

[sidebar]
.Multiply and Divide
--
When we are computing, we express math in a slightly different way than we do in Algebra class.
Take your mind back to Mrs Johnson's 7th grade algebra class. 
(Weren't all our 7th grade algebra teachers named Mrs Johnson?? No? Are you sure?)

In algebra, we might say *4x* or *3x*. We mean, of course, *4 times x* or *3 times x*.

Well, in coding we usually write `3 * x` or `4 * x` - the *** (an asterisk or shift-8 on your keyboard) means *multiply* or *times*.

Division, too is different. In algebra we used the old divide sign *รท* whenever we divided *9 รท 4*, but in JavaScript code we use a slash */*.
So, *5 divided by 2* is written *5 / 2*.

It's okay, you'll get used to *** and */* for times and divide.
--

----
Given the following formula,
 
y = (5 * x) + 100

what is y, if x = 3?
----

For each of these problems, you need to compute the value of *y*. 
In each case the value of *x* is different, and so is the formula you need to compute.

For this first one, if *x equals 3*, you would first multiply *5* times *3*, and then add 100 to it.
So a correct answer is *15 + 100* or *115*.

Each of these below are computed in pretty much the same way.

==== ?

----
Given the following formula,
 
y = (4 * x) - 5

what is y, if x = 5?
----

==== ?

----
Given the following formula,
 
y = (6 * x) - 7

what is y, if x = 2?
----

==== ?

----
Given the following formula,
 
y = (15 / x) * 8

what is y, if x = 5?
----

=== Velocities

Velocity is often thought of as *speed*. It's common to drive at 40 or 45 miles per hour.
That speed is a *velocity*.
*Acceleration*, you may remember, is the change in velocity.

If a car is moving at an initial velocity V, and accelerates at rate of A for a set time 
period of T, the formula to determine it final velocity S is: 

****
S = A*T + V
****

So if we have a *A=2*, *T=3*, and *V=4*, we would compute 
****
S = (2 * 3) + 4

S = 6 + 4

S = 10
****

You substitute each variable (V, A and T) into the formula and compute the result.

==== ?

----
What is S if (V = 10), (A = 4), (T = 3)?
----

==== ?

----
What is S if (V = 0), (A = 5), (T = 20)?
----

==== ?

----
What is S if (V = 17), (A = 2), (T = 14)?
----

=== F of x or F(x)

Sometimes you will see a formula expressed as a function which takes one parameter, *x*. 
an _parameter_ to a function is it's input value.
This is an algebraic (or math) function, not a Javascript function.

****
F(x) = 3x + 4
****

This is just another way of describing a simple computation.
The result of the function, F(x) (which is pronounced _F of x_), is the same as *y* was
in the problems above.

****
y = 3x + 4
****

*Y* ended up being the answer to the computation. 
So is _F of x_ is also the answer to the computation.
Don't overthink this, *y* and *f of x* are just two ways of saying the same thing.

The other thing to notice is the *3x* portion. In JavaScript, you need to change it to *3 * x* so a correct form of a JavaScript function would be 

----
function f(x) {
    return (3 * x) + 4;
}
----

Write out these three formulas as JavaScript functions.
Use the example above to help with your answers.

==== ? 

****
f(x) = 5x - 7
****

==== ?

****
g(x) = 6x + 3
****

==== ?

****
h(x) = 123x - 68
****


[sidebar]
.Parameters and Arguments
--
As you learn to code, you will be using this thing called a *function*. 
Functions are the main *building blocks* of a program. 
They allow the code to be called many times without repetition.

So, a programmer bundles up smaller pieces of their program into functions.

In JavaScript, and many other programming languages (yes, there are many!), we often need to supply a function with data.
And that data can often change.

When we supply a function with data, we *pass* some *parameters* to the function.

Say I have a function that does something really simple, it takes a number a divides it by 2:
[source]
----
function halve(x) {
    return x / 2;
}
----

In this example, *x* is a *parameter*. It is also called an *argument*.
I'll try to use *parameter* throughout this booklet, but in some problems you may see on-line,
you may also see *x* in the above function described as an *argument*.
--

=== F of (x, y)

Well, so if *F of x* is the result of a function of one parameter *x*, *F of x and y* is also the result of a function.
But in this case, the functions takes two parameters, *x* and *y*.

Given the following function using x and y: 

**** 
F(x, y) = 2x + y -27
****

And then if _F(1, 2) = -23_, well, how did we get that result?

The idea is that you think it through like this:

****
given F(1, 2), we assign x=1 and y=2 and substitute these two variables to compute the result.

F(1,2) = (2 * x) + y - 27

F(1,2) = (2 * 1) + 2 - 27

F(1,2) = 2 + 2 - 27

F(1,2) = 23
****

Using that as a *pattern*, work through these problems:

==== ?

****
f(20, 8) = ?
****

==== ?

****
f(6, 25) = ?
****

==== ?

****
f(5, 2) = ?
****

==== ?

****
f(0, 0) = ?
****

=== Complete the answer

For this problem, you need to figure out the correct answer to the last expression. 

----
dog + fish = 25
dog + bird = 35
bird + fish = 30
----

If the above expressions are true, what is the answer to this?

----
dog + bird + fish = ?
----

